packages:
  - backend
  - frontend
  - lib

verifyDepsBeforeRun: false

allowBuilds:
  '@nestjs/core': true
  '@openapitools/openapi-generator-cli': true
  '@prisma/engines': true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
  workerd: true

overrides:
  '@typescript-eslint/typescript-estree>semver': '7.3.8'
  'eslint>minimatch': '3.1.5'
  'eslint>brace-expansion': '1.1.11'
  '@eslint/config-array>minimatch': '3.1.5'
  '@eslint/config-array>brace-expansion': '1.1.11'
  '@eslint/eslintrc>minimatch': '3.1.5'
