// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { listLocalDatabases } from '@prisma/adapter-d1';
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

function getLocalDatabaseUrl(): string {
  try {
    const databases = listLocalDatabases();
    const db = databases.find((name) => !name.includes('metadata')); // wrangler d1 creates a metadata database we want to ignore
    if (db) {
      console.log(`Using local D1 database: ${db}`);
      return `file:${db}`;
    }
  } catch {
    // In CI or environments without .wrangler directory, fall back to a dummy URL.
    // prisma generate only needs the schema, not a real database connection.
  }
  return 'file:./prisma/placeholder.db';
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: getLocalDatabaseUrl(),
  },
});
